### ISSUE TITLE
Asciicast documentation

### ISSUE THREAD

**Issue by pocc** [dcoles/asciicast-tools#1]
Can you add an Asciicast of usage in the README? It feels ...empty without it.

**Comment by dcoles** [comment]
Updated the README to include a small `Usage` snippet and some more examples of how to
use `asciicast-pipe` (renamed from `asciicast`) to prevent confusion.

`asciicast-pipe` isn't really all that useful on its own, it really needs to be paired up with another tool like `tmux pipe-pane`, `script` or `scriptreplay` to be able to capture output. However I've also added a `--force-cr` (`-r`) flag that can be used to record output from regular Unix applications.

Let me know if the README still needs some improvement.

**Comment by pocc** [comment]
Appreciate it. The documentation that you've added helps to add context. 

I'm still curious about `tmux-asciicast-pane`. I know what tmux, but not why you would use this tool vs. just normal `asciinema rec`. Can you add a picture/asciicast of usage to the README that demonstrates it? A sentence or two of motivation would also help.

**Comment by dcoles** [comment]
Originally this project was started as a way of recording from a tmux session using `tmux pipe-pane`. After doing some research I found out there was already the asciicast format, so figured it made sense to use that as the interchange format.

As for the question of why not just use `asciinema rec`, I can give a couple of reasons. First, recording directly from a tmux pane means you can [start recording without needing to start a new shell session](https://github.com/dcoles/asciicast-tools/blob/master/README.md#binding-to-a-tmux-key) (for example the output of an already running program). Second, I like the idea of small programs that do one thing and one thing well. Finally (the most selfish reason) is I just wanted to see if it was possible to do 😊.

**Comment by pocc** [comment]
Dude this is **perfect**. Add this comment to an `## Introduction` section and close this issue.

Cheers also on adding an Asciicast.

**Comment by dcoles** [comment]
Glad to hear that. Thank you for your feedback and helping to improve the documentation.
