### ISSUE TITLE
🥾 _b00t_ emoji characters don't render in PREVIEW THUMBNAIL (but work fine in asciinema) 

### ISSUE THREAD

**Issue by elasticdotventures** [dcoles/asciicast-tools#2]
I have no idea who to report this to (not sure who is responsible for the github markdown), but Emoji doesn't preview correctly on the github previews of the asciicast. 

The actual RENDER video on asciinema works fine, just the thumbnail preview shows UTF8 escape sequences for non-western characters (though it seems to show chinese pinyin fine)?

preview:
[http://github.com/elasticdotventures/_b00t_](http://github.com/elasticdotventures/_b00t_)

I will try to debug more on my own, but would appreciate any advice in the proper direction to get this resolved.  Thanks! 

---

Look at the screwball character codes in the video below, then watch the video. 

[![asciicast](https://asciinema.org/a/QxGcR4JrvSI6ReVi4dhwsYkUP.png)](https://asciinema.org/a/QxGcR4JrvSI6ReVi4dhwsYkUP)

**Comment by dcoles** [comment]
Hi! Thanks for your report.

I believe you want to file a bug about thumbnails generated by https://asciinema.org.

This repository (`asciicast-tools`) is a third-party project and does not contain any code used in https://asciinema.org.
You're probably looking for the https://github.com/asciinema/asciinema-server project.

Please feel free to reopen this bug if you think it has been closed in error.
